local builtin = require('telescope.builtin')
local plugin = require("plugin")
vim.keymap.set('n', '<F6>', plugin.anime_selector, {})
vim.keymap.set('n', '<leader>i', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>lg', builtin.live_grep, {})

